### ISSUE TITLE
Shulker Box

### ISSUE THREAD

**Issue by Kade-N** [KyleNecrowolf/Revival#21]
For some strange reason, Minecraft needs a separate 3-row inventory texture for shulker boxes, despite it being identical to every other 3-row inventory which doesn't require a texture. 

Since it's separate, might as well do end colours instead of the brown for chests. 

![shulker_box](https://cloud.githubusercontent.com/assets/20824272/26468773/9961971a-4165-11e7-82f6-6d83010bae3e.png)

**Comment by Maisa85** [comment]
![shulker_box](https://user-images.githubusercontent.com/29552408/39406899-d855ad96-4bc6-11e8-991a-49d07e7348bb.png)

**Comment by GalvinGreene** [comment]
Hey Maisa, can you email me all the texture you have made in a .zip file.  It is probably going to give us weird download artifacts from downloading it here.

**Comment by Maisa85** [comment]
Sure, here you go. There are few extras, I made "conquest copy" shulker
boxes from SMP's material back in the day and re-made carrot and pumpkin
pie items with original color palette. Also the attack cool-down indicator
is included in icons.
I suggest you change at least the beetroots because the previous ones were
"borrowed" from Beyond Lands textures. (I originally made a mix-up pack for
my own use and forgot they were there)
The concrete powders were colored with the new concrete blocks aside but I
couldn't make pink and light blue as precise as I would have wanted.
About the lite-version.. I already have one made for my own use, I can
upload it too but I have to check that first for those other packs textures.

2018-05-02 10:26 GMT+03:00 GalvinGreene <notifications@github.com>:

**Comment by Maisa85** [comment]
​Few more here, made some corrections. Ghasts ass was not properly mapped
etc.​

2018-05-02 11:25 GMT+03:00 Maisa Kauppinen <coolmaisa@gmail.com>:
