### ISSUE TITLE
Wolves

### ISSUE THREAD

**Issue by loriloves** [KyleNecrowolf/Revival#42]
missing a texture

**Comment by Kade-N** [comment]
We have a few wolf textures made by SMP, but they are intentionally disabled, as having pets change color constantly is not ideal, and I found they didn't look wolf-like enough in terms of color (brown or white). 

I might look into making a wolf texture that looks more grey-wolf while fitting the SMP style.

**Comment by loriloves** [comment]
Alright that makes sense, i just noticed while taming a few wolves that
they were missing the original textures. I think a SMP style grey wolf
would look really cool.

**Comment by Maisa85** [comment]
I'll just leave these here.


2018-03-25 0:10 GMT+02:00 loriloves <notifications@github.com>:

**Comment by Maisa85** [comment]
I'll just leave these here..

![wolf](https://user-images.githubusercontent.com/29552408/38025866-a4037cc8-3292-11e8-8e8e-3445e9bf898d.png)
![wolf_angry](https://user-images.githubusercontent.com/29552408/38025867-a43b8eb0-3292-11e8-9ec4-54b87d1c805b.png)
![wolf_tame](https://user-images.githubusercontent.com/29552408/38025868-a45c6608-3292-11e8-8de4-a2c2629268a6.png)
![wolf 1](https://user-images.githubusercontent.com/29552408/38025874-a93607ec-3292-11e8-83e5-ab1be42bc362.png)
![wolf_angry 1](https://user-images.githubusercontent.com/29552408/38025875-a953fb9e-3292-11e8-92d3-d143d3721688.png)
![wolf_tame 1](https://user-images.githubusercontent.com/29552408/38025876-a97692e4-3292-11e8-90e2-caec9ef4baa9.png)

**Comment by loriloves** [comment]
Thank you I definitely prefer these over vanilla.

**Comment by Kade-N** [comment]
I'm adding those to the pack, as alternates right now. They are in the minecraft entity folder (no random mobs, because it doesn't work well for pets), rename the one you prefer to use to just "wolf".

The current ones include:
- SMP Brown (original default)
- SMP Light (previously random)
- SMP Dark (previously random)
- Maisa Light (posted above)
- Maisa Dark (posted above)

I'm leaning towards Maisa Light as the new default, I think it fits the pack style best, and isn't overly light or dark. I may tweak the face and colours a bit, just darken the fur and eyes slightly, and maybe add the brown around the mouth like the dark one. 

In-game pictures of Maisa Light:
![image](https://user-images.githubusercontent.com/20824272/38404384-aea01bc2-3937-11e8-9c6e-3d6829559999.png)
![image](https://user-images.githubusercontent.com/20824272/38404423-fe109bf0-3937-11e8-8169-52c762521e3d.png)

**Comment by Kade-N** [comment]
Here's what I came up with. Minor edits to Maisa Light, 
Eye now has the third top pixel on the tamed wolf (same as vanilla wolf), and they're now a grey-yellow colour, which I think looks much more natural. The near-white pixel was annoying me so much in the five textures we had. 
I also brought the brown muzzle over from Maisa Dark. Gives some more detail and personality to the lower face. 
![image](https://user-images.githubusercontent.com/20824272/38405833-e9e2ff1c-393f-11e8-84c4-219b482fe42b.png)
![image](https://user-images.githubusercontent.com/20824272/38405865-22097092-3940-11e8-801d-2ca5dad2345b.png)
![image](https://user-images.githubusercontent.com/20824272/38405870-2597ada0-3940-11e8-817f-e0d6292d12c9.png)

**Comment by Kade-N** [comment]
Here's the normal wolf:
![image](https://user-images.githubusercontent.com/20824272/38406381-a4776eb0-3942-11e8-8d57-5e81bd14ce84.png)
![image](https://user-images.githubusercontent.com/20824272/38406385-a74ccb12-3942-11e8-9a0c-9e25f950a142.png)

And angry wolf (now with less laser eyes):
![image](https://user-images.githubusercontent.com/20824272/38406401-bd658bfa-3942-11e8-8642-b95b8799ac02.png)

Finally, here are the actual textures, normal, angry, tamed:
![wolf](https://user-images.githubusercontent.com/20824272/38406460-027b35f0-3943-11e8-8917-544d84d6709f.png)![wolf_angry](https://user-images.githubusercontent.com/20824272/38406464-067a1a40-3943-11e8-98e1-bc28bd181263.png)![wolf_tame](https://user-images.githubusercontent.com/20824272/38406467-0af5ba16-3943-11e8-8535-d6a2c23797be.png)

I am adding these as the default wolf textures for the pack. The other five will remain as alternates.
